# Generated by Django 5.2.4 on 2025-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especialidad', models.CharField(choices=[('RH', 'Recursos Humanos'), ('ELO', 'Electrónica'), ('POG', 'Programación'), ('GE', 'Gericultura')], default='RH', max_length=100)),
                ('matricula', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
